language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3

android:

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

  components:
    - tools
    - platform-tools

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL

before_install:
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;29.0.3"

script:
  - ./gradlew build check